### ISSUE TITLE
make private properties truly private

### ISSUE THREAD

**Issue by GypsyDangerous** [GypsyDangerous/twitchio-js#4]
this is a an easy thing to do and I am just to lazy to do it. for all the properties of the TwitchApi class that are marked as private 
```ts
private clientId?: string;
private authorizationKey?: string;
private clientSecret?: string;
private Kraken: boolean;
```
need to have an underscore appended to the start and then we need getter functions for all of them and I think we only need a setter for the Kraken option because that is the only option I want to make changeable

**Comment by meghanmae** [comment]
I'm looking for some things to do for hacktoberfest. I can take this on once that starts up!

**Comment by GypsyDangerous** [comment]
awesome 😀
